# Generated by Django 5.0 on 2023-12-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_remove_users_permissions_remove_users_roles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='teams',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='teams', to='task_app.projects'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='teams', to='task_app.tasks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='users', to='task_app.tasks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='users', to='task_app.teams'),
        ),
    ]
